# vim:ft=ansible:
---
- name: manage users and groups
  hosts: bastion 
  sudo: yes
  tasks:

  - name: ensure the sysadmin group is on the host
    group: name=sysadmin state=present
  
  # User Gert Leenders
  - name: ensure user Gert leenders is on the host as sysadmin
    user: name=glnds comment="Gert Leenders" uid=2001 group=sysadmin shell=/bin/bash
  
  - name: ensure the public key for Gert Leenders is on the host
    authorized_key: user=glnds key="{{ lookup('file', 'files/public_keys/glnds.pub') }}"  
