# vim:ft=ansible:
---
- name: manage users and groups
  hosts: ci-server
  sudo: Yes
  tasks:

  - name: ensure the sysadmin group is on the host
    group: name=sysadmin state=present
  
  # User Gert Leenders
  - name: ensure user Gert leenders is on the host as sysadmin
    user: name=glnds comment="Gert Leenders" uid=2001 group=sysadmin shell=/bin/bash
  
  - name: ensure the public key for Gert Leenders is on the host
    authorized_key: user=glnds key="{{ lookup('file', 'files/public_keys/glnds.pub') }}"  

  - name: allow sudo without password
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sysadmin(\s*)ALL'
      line: '%sysadmin     ALL=(ALL)       NOPASSWD: ALL'
      insertafter: '^root(\s*)ALL'
