# vim:ft=ansible:
---
- name: VPC setup
  hosts: localhost
  gather_facts: False
  tasks:

  - name: ensure the vpc and subnets present
    ec2_vpc:
      state: present
      region: "{{ region }}"
      profile: "{{ profile }}"
      internet_gateway: True
      resource_tags: { Name: "vpc-{{ name_prefix }}", Stack: "{{ stack }}" }
      cidr_block: 100.0.0.0/16
      wait: yes
      subnets:
        - cidr: 100.0.0.0/20
          az: eu-west-1a
          resource_tags: { Name: "{{ name_prefix }}_private_1a", Stack: "{{ stack }}" }
        - cidr: 100.0.16.0/24
          az: eu-west-1a
          resource_tags: { Name: "{{ name_prefix }}_public_1a", Stack: "{{ stack }}" }
        - cidr: 100.0.64.0/20
          az: eu-west-1b
          resource_tags: { Name: "{{ name_prefix }}_private_1b", Stack: "{{ stack }}" }
        - cidr: 100.0.80.0/24
          az: eu-west-1b
          resource_tags: { Name: "{{ name_prefix }}_public_1b", Stack: "{{ stack }}" }
    register: vpc

  - name: add the vpc id to the list of global variables
    lineinfile:
      dest: "{{ inventory_dir }}/group_vars/all.yml"
      regexp: "^vpc_id:"
      line: "vpc_id: {{ vpc.vpc_id }}"

  - name: add the subnet ids to the list of global variables
    lineinfile:
      dest: "{{ inventory_dir }}/group_vars/all.yml"
      regexp: "^{{ item.resource_tags.Name }}:"
      line: "{{ item.resource_tags.Name }}: {{ item.id }}"
    with_items: vpc.subnets

  - name: find public subnet 1a
    set_fact: vpc_subnet_id="{{ item.id }}"
    when: item.resource_tags.Name == "{{ name_prefix }}_public_1a"
    with_items: vpc.subnets

  - name: store the subnet name variables
    set_fact: "{{ item.resource_tags.Name }}={{ item.id }}"
    with_items: vpc.subnets

  - include: vpc_security.yml
 
  - include: vpc_bootstrap_bastion.yml

  - include: vpc_bootstrap_webservers.yml
