# vim:ft=ansible:
---
- name: VPC setup
  hosts: localhost
  gather_facts: False
  vars:
    region: eu-west-1
    profile: pixxis
    name_prefix: staging
    instance_name_prefix: s
    stack: Development
    key_name: TestKP
    zone: pixxis.be
  tasks:

  - name: ensure the vpc, subnets, internet gateway and route table are present
    ec2_vpc:
      state: present
      region: "{{ region }}"
      profile: "{{ profile }}"
      internet_gateway: True
      resource_tags: { Name: "vpc-{{ name_prefix }}", Stack: "{{ stack }}" }
      cidr_block: 100.0.0.0/16
      wait: yes
      subnets:
        - cidr: 100.0.0.0/20
          az: eu-west-1a
          resource_tags: { Name: "{{ name_prefix }}-private-1a", Stack: "{{ stack }}" }
        - cidr: 100.0.16.0/24
          az: eu-west-1a
          resource_tags: { Name: "{{ name_prefix }}-public-1a", Stack: "{{ stack }}" }
        - cidr: 100.0.64.0/20
          az: eu-west-1b
          resource_tags: { Name: "{{ name_prefix }}-private-1b", Stack: "{{ stack }}" }
        - cidr: 100.0.80.0/24
          az: eu-west-1b
          resource_tags: { Name: "{{ name_prefix }}-public-1b", Stack: "{{ stack }}" }
      route_tables:
        - subnets:
          - 100.0.16.0/24
          - 100.0.80.0/24
          routes:
          - dest: 0.0.0.0/0
            gw: igw
    register: vpc

  - name: add the vpc id to the list of global variables 
    lineinfile:
      dest: "{{ inventory_dir }}/group_vars/all.yml" 
      regexp: "^vpc_id:"
      line: "vpc_id: {{ vpc.vpc_id }}"

  - name: find public subnet 1a
    set_fact: vpc_subnet_id="{{ item.id }}"
    when: item.resource_tags.Name == "{{ name_prefix }}-public-1a"
    with_items: vpc.subnets

  - include: vpc_security.yml
 
  - include: vpc_bastion.yml 
