# vim:ft=ansible:
---
- name: ensure the bastion security group is present
  ec2_group:
    name: BastionSG
    description: Bastion security group
    vpc_id: "{{ vpc.vpc_id }}"
    profile: "{{ profile }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0 
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
  register: bastion_sg

- name: tag the bastion security group
  ec2_tag:
    profile: "{{ profile }}"
    resource: "{{bastion_sg.group_id}}"
    region: "{{ region }}"
    state: present
    tags:
      Name: "BastionSG"
      Stack: "{{ stack }}"

- name: ensure the webserver security group is present
  ec2_group:
    name: WebserverSG
    description: Webserver security group
    vpc_id: "{{ vpc.vpc_id }}"
    profile: "{{ profile }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        group_id: "{{ bastion_sg.group_id }}"
      - proto: tcp
        from_port: 80
        to_port: 80
        group_id: "{{ bastion_sg.group_id }}"
      - proto: tcp
        from_port: 443
        to_port: 443
        group_id: "{{ bastion_sg.group_id }}"
    rules_egress:
      - proto: tcp
        from_port: 80
        to_port: 80
        group_id: "{{ bastion_sg.group_id }}"
      - proto: tcp
        from_port: 443
        to_port: 443
        group_id: "{{ bastion_sg.group_id }}"
  register: webserver_sg

- name: tag the webserver security group
  ec2_tag:
    profile: "{{ profile }}"
    resource: "{{ webserver_sg.group_id }}"
    region: "{{ region }}"
    state: present
    tags:
      Name: "WebserverSG"
      Stack: "{{ stack }}"

- name: ensure the bastion securty group's wwebserver rules are configured
  ec2_group:
    name: BastionSG
    description: Bastion security group
    vpc_id: "{{ vpc.vpc_id }}"
    profile: "{{ profile }}"
    region: "{{ region }}"
    purge_rules: False
    purge_rules_egress: False
    rules_egress:
      - proto: tcp
        from_port: 22
        to_port: 22
        group_id: "{{ webserver_sg.group_id }}"

- name: ensure the ecs container instances security group is present
  ec2_group:
    name: ECSContainerSG
    description: ECSContainer security group
    vpc_id: "{{ vpc.vpc_id }}"
    profile: "{{ profile }}"
    region: "{{ region }}"
  register: ecscontainer_sg

- name: tag the ecs container security group
  ec2_tag:
    profile: "{{ profile }}"
    resource: "{{ ecscontainer_sg.group_id }}"
    region: "{{ region }}"
    state: present
    tags:
      Name: "ECSContainerSG"
      Stack: "{{ stack }}"
